# Basic
title: LYY
subtitle: 喜欢装逼的OIer
welcome_message: Hello World
description: 这次修改的代码没有污染
creator: <a href="http://yangyanghou.xyz">@onevcat</a>

url: "http://dgslyy.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 洛谷博客, description: Luogu Blog, url: 'https://www.luogu.org/blog/dgslyy/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: dglyy
    github: dgslyy
    twitter: dgslyy
    mail: 2858853716@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman